#!/bin/bash

# VirtualBox Power Driver for MAAS (Metal as a Service)
# Copyright 2021 Saeid Bostandoust <ssbostan@linuxmail.org>

echo "INFO: Welcome to VirtualBox Power Driver for MAAS (vboxpower)"

which python3 &> /dev/null

if [ $? -ne 0 ]; then
    echo "ERROR: Python3 is not installed."
    exit 1
fi

which pip3 &> /dev/null

if [ $? -ne 0 ]; then
    echo "ERROR: Pip3 is not installed."
    exit 1
fi

which virtualbox &> /dev/null

if [ $? -ne 0 ]; then
    echo "ERROR: VirtualBox is not installed."
    exit 1
else
    echo "INFO: VirtualBox is installed on the system."
fi

pip3 freeze | grep vboxapi &> /dev/null

if [ $? -ne 0 ]; then
    echo "ERROR: VirtualBox SDK is not installed."
    exit 1
else
    echo "INFO: VirtualBox SDK is installed on the system."
fi


# Prepare the directory
mkdir -p /opt/maas/vboxpower

# Define the path and name for your virtual environment
venv_path="/opt/maas/vboxpower/venv"

# Create the virtual environment
python3 -m venv "$venv_path"

# Activate the virtual environment
source "$venv_path/bin/activate"

# Install packages from requirements.txt
pip install -r requirements.txt &> /dev/null

if [ $? -ne 0 ]; then
    echo "ERROR: Cannot install the required packages."
    exit 1
else
    echo "INFO: Required packages are installed successfully."
fi

# Deactivate the virtual environment
deactivate

# Copy the vboxpower application and wrapper script with its dependencies
cp vboxpower.py /opt/maas/vboxpower/vboxpower.py
cp start_gunicorn.sh /opt/maas/vboxpower/start_gunicorn.sh

# Setup systemd service file
cp vboxpower.service /etc/systemd/system/vboxpower.service

# Reload systemd, enable and start the vboxpower service
systemctl daemon-reload
systemctl enable --now vboxpower.service
systemctl restart vboxpower.service

if systemctl -q is-active vboxpower.service; then
    echo "INFO: vboxpower service started successfully."
else
    echo "ERROR: Failed to start vboxpower service."
    systemctl status vboxpower.service
    exit 1
fi

